export const DEDICATED_WORKER_PATH = '/dedicated-worker.js'
export const SHARED_WORKER_PATH = '/shared-worker.js'
export const SW_CORE_PATH = '/sw-core.js'
export const SW_FILENAME = 'sw.js'
export const SW_PATH = '/sw.js'
