name: CI
on:
  push:
    branches:
      - "main"
    tags: ["*"]
env:
  ROOT_DOMAIN: strn.pl
jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Build
        env:
          STATIC_ORIGIN: https://saturn.tech
          L1_ORIGIN: https://l1s.saturn.ms
          TRUSTED_L1_ORIGIN: https://saturn.ms
          UNTRUSTED_L1_ORIGIN: https://l1s.saturn.ms
          LOG_INGESTOR_URL: https://twb3qukm2i654i3tnvx36char40aymqq.lambda-url.us-west-2.on.aws
        run: |
          npm ci
          npm run build

      - uses: EndBug/add-and-commit@v9
        if: github.ref_type == 'tag'
        with:
          add: "dist"
          default_author: user_info
          message: "CI Build"
          push: origin HEAD:main

      - name: Trigger ./dist/* file replication in filecoin-saturn/homepage repo
        if: github.ref_type == 'tag'
        run: |
          code="$(curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{secrets.ACCESS_TOKEN}}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/filecoin-saturn/homepage/actions/workflows/copy-retrieval-client-files.yml/dispatches \
          -d '{"ref": "main"}' \
          -sw "%{http_code}\n")"

          test "$code" -eq 204 || exit 1
