name: CI
on:
  push:
    branches:
      - "main"
    tags: ["*"]
jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm ci

      - name: Run Tests
        run: npm run test

      # Just checking if build succeeds.
      - name: Build
        env:
          STATIC_FILE_ORIGIN: https://saturn-test.network
          L1_ORIGIN: https://l1s.saturn-test.ms
          TRUSTED_L1_ORIGIN: https://saturn-test.ms
          LOG_INGESTOR_URL: https://p6wofrb2zgwrf26mcxjpprivie0lshfx.lambda-url.us-west-2.on.aws
          JWT_AUTH_URL: https://fz3dyeyxmebszwhuiky7vggmsu0rlkoy.lambda-url.us-west-2.on.aws/
          ORCHESTRATOR_URL: https://orchestrator.strn-test.pl/nodes?maxNodes=100
        run: npm run build
